#! /bin/bash
TITULO="Kloxo-MR Install"
##################################### V A R I A B L E ###########################################################
MAILSOPORTE="admin@ipcloud.com.ar" MAILCLIENTE="cliente@dnsargentina.com.ar"
UPTIME="U P T I M E:`uptime`" EQUIPO="E Q U I P O: `hostname -f`"
LINEA="------------------------------------------- IP C L O U D ----------------------------------------------------"
##################################### F I N N N N ###############################################################
cd /
pwd
yum remove -y samba
yum update -y && yum upgrade -y
yum install vim yum-utils yum-priorities vim-minimal subversion curl zip unzip telnet wget -y
setenforce 0
echo "SELINUX=disabled" > /etc/selinux/config
cd /etc/yum.repos.d/
wget https://github.com/mustafaramadhan/kloxo/raw/release/kloxo-mr.repo --no-check-certificate
cd /
yum install kloxomr -y
sh /script/upcp
/script/version >> /tmp/kloxo-install.log
LXLOG=/tmp/kloxo-install.log
############################################################################################################
if [ -s $LXLOG ]; then                                                                                     #
mail -s "$TITULO `hostname -f`"  $MAILCLIENTE < $LXLOG                                                     #
mail -s "$TITULO `hostname -f`"  $MAILSOPORTE < $LXLOG                                                     #
rm $LXLOG                                                                                                  #
fi                                                                                                         #
############################################################################################################
